on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  if_merged:
    if: (github.head_ref == 'feature/theMegaComment')
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo merge from the MegaComment