on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  if_merged:
    if: ((startsWith(github.head_ref, 'feature') || startsWith(github.head_ref, 'hotfix') || startsWith(github.head_ref, 'release')) && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo merge from the MegaComment
               