on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:

  merge-to-develop:
    runs-on: ubuntu-latest
    if: ((startsWith(github.head_ref, 'feature') || startsWith(github.head_ref, 'hotfix') || startsWith(github.head_ref, 'release')) && github.event.pull_request.merged == true)
    steps:
      - uses: actions/checkout@master

      - name: ${github.head_ref} -> develop 
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: ${{ github.head_ref }}
          target_branch: develop
          github_token: ${{ github.token }}

  test:
    runs-on: ubuntu-latest
    needs: merge-to-develop
    steps:
      - name: echoing 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          echo Hello world


  
               